[colors.bright]
black = "0x767676"
blue = "0x3b78ff"
cyan = "0x61d6d6"
green = "0x16c60c"
magenta = "0xb4009e"
red = "0xe74856"
white = "0xf2f2f2"
yellow = "0xf9f1a5"

[colors.normal]
black = "0x0c0c0c"
blue = "0x0037da"
cyan = "0x3a96dd"
green = "0x13a10e"
magenta = "0x881798"
red = "0xc50f1f"
white = "0xcccccc"
yellow = "0xc19c00"

[colors.primary]
background = "0x0c0c0c"
foreground = "0xcccccc"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
style = "SemiBold"

[font.bold_italic]
style = "SemiBold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Command"

[window]
opacity = 1.0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
