local keymap = require("gb-utils").map
keymap("n", "<leader>da", ":call vimspector#Launch()<CR>")
keymap("n", "<leader>dd", ":TestNearest -strategy=jest<CR>")
keymap("n", "<leader>dc", ":call GotoWindow(g:vimspector_session_windows.code)<CR>")
keymap("n", "<leader>dv", ":call GotoWindow(g:vimspector_session_windows.variables)<CR>")
keymap("n", "<leader>dw", ":call GotoWindow(g:vimspector_session_windows.watches)<CR>")
keymap("n", "<leader>ds", ":call GotoWindow(g:vimspector_session_windows.stack_trace)<CR>")
keymap("n", "<leader>do", ":call GotoWindow(g:vimspector_session_windows.output)<CR>")
keymap("n", "<leader>d?", ":call AddToWatch()<CR>")
keymap("n", "<leader>dx", ":call vimspector#Reset()<CR>")
keymap("n", "<leader>dX", ":call vimspector#ClearBreakpoints()<CR>")
keymap("n", "<S-h>", ":call vimspector#StepOut()<CR>")
keymap("n", "<S-l>", ":call vimspector#StepInto()<CR>")
keymap("n", "<S-j>", ":call vimspector#StepOver()<CR>")
keymap("n", "<leader>d_", ":call vimspector#Restart()<CR>")
keymap("n", "<leader>dn", ":call vimspector#Continue()<CR>")
keymap("n", "<leader>drc", ":call vimspector#RunToCursor()<CR>")
keymap("n", "<leader>dh", ":call vimspector#ToggleBreakpoint()<CR>")
keymap("n", "<leader>de", ":call vimspector#ToggleConditionalBreakpoint()<CR>")
vim.g.vimspector_base_dir = vim.fn.expand("$HOME/.config/nvim/vimspector-config")
vim.g.vimspector_sidebar_width = 120
vim.g.vimspector_bottombar_height = 10
