#!/bin/zsh

SESSION_NAME=gregCoffee
DIRECTORY=~/greg.coffee

if ! tmux has-session -t $SESSION_NAME; then
	TMUX= tmux new-session -d -s $SESSION_NAME -n website -c $DIRECTORY

	tmux select-window -t$SESSION_NAME:1
	tmux split-window -h -c $DIRECTORY
	tmux resize-pane -t 2 -x 80
	tmux select-pane -t 1
	tmux send-keys -t$SESSION_NAME:1 "cd $DIRECTORY" "C-m"
	tmux send-keys -t$SESSION_NAME:1 "vim" "C-m"
fi

tmux -2 attach -t $SESSION_NAME

