#!/bin/zsh

SESSION_NAME=radish
RBUILD=~/radish/build
RADMIN=~/radish/build/admin
RNEWBACK=~/radish/new-backend


if ! tmux has-session -t $SESSION_NAME; then
	TMUX= tmux new-session -d -s $SESSION_NAME -n new-backend -c $RBUILD
	tmux new-window -t$SESSION_NAME:2 -c $RADMIN -n admin

	tmux select-window -t$SESSION_NAME:1
	tmux send-keys -t$SESSION_NAME:1 "vim" "C-m"

	tmux select-window -t$SESSION_NAME:2
	tmux send-keys -t$SESSION_NAME:2 "vim" "C-m"

	tmux select-window -t$SESSION_NAME:1
fi
tmux -2 attach -t $SESSION_NAME

